### ISSUE TITLE
Share trained model.

### ISSUE THREAD

**Issue by hASEEBjAN** [defeatcovid19/defeatcovid19-net-pytorch#2]
Would it be possible to share a trained models. I have a protype of both types of mobile apps i-e object detection and classification. I want to implement it in my flutter app and publish it as a Minimal Viable Product 
Thanks.

**Comment by mrtj** [comment]
Hello. I successfully retrained the model on a single not-so-new GPU (GTX 1080) in approximately 10 minutes, so having the model yourself really should not be a big issue.

**Comment by thundo** [comment]
Hi @hASEEBjAN,

yes, training is very fast. If you run the script weights are automatically saved while training every few epochs or at the end in `pth` format.

**Comment by hASEEBjAN** [comment]
Thanks and yup in a mean time I also do on my own. It is fast.
